version: '3.8'

services:
  webapp:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./static/data:/app/static/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: